<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.huanniankj</groupId>
        <artifactId>uba-x</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>
    <artifactId>ubax-module-pilot</artifactId>

    <name>${project.artifactId}</name>
    <description>
        数据采集探针模块，负责与 UBAX-Pilot 通讯等操作。
    </description>

    <dependencies>
        <!-- Web 相关 -->
        <dependency>
            <groupId>com.huanniankj</groupId>
            <artifactId>ubax-spring-boot-starter-web</artifactId>
        </dependency>

        <!-- 安全权限 (因为要提供给后台管理系统调用) -->
        <dependency>
            <groupId>com.huanniankj</groupId>
            <artifactId>ubax-spring-boot-starter-security</artifactId>
        </dependency>

        <!-- DB 相关，引入 MyBatis Plus 进行数据查询 -->
        <dependency>
            <groupId>com.huanniankj</groupId>
            <artifactId>ubax-spring-boot-starter-mybatis</artifactId>
        </dependency>

        <!-- Hutool 等工具类 -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.25</version>
        </dependency>

        <!-- 基础依赖 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

</project>
